from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Protocol, Any


@dataclass(slots=True)
class BackendCapabilities:
    pause_resume: bool = False
    read_registers: bool = False
    read_memory: bool = False
    disassemble: bool = False
    list_memory_maps: bool = False
    take_snapshot: bool = False
    restore_snapshot: bool = False
    trace_basic_block: bool = False
    trace_branch: bool = False
    trace_memory: bool = False
    trace_syscall: bool = False
    run_until_address: bool = False
    single_step: bool = False

    def to_dict(self) -> dict[str, bool]:
        return asdict(self)


class BackendAdapter(Protocol):
    def start(
        self,
        target: str,
        args: list[str],
        cwd: str | None,
        qemu_config: dict[str, Any] | None = None,
    ) -> None: ...

    def resume(self, timeout: float) -> dict[str, Any]: ...
    def pause(self, timeout: float) -> dict[str, Any]: ...
    def run_until_event(self, event_types: list[str], timeout: float) -> dict[str, Any]: ...
    def run_until_address(self, address: str, timeout: float) -> dict[str, Any]: ...
    def step(self, count: int, timeout: float) -> dict[str, Any]: ...
    def advance_basic_blocks(self, count: int, timeout: float) -> dict[str, Any]: ...
    def get_registers(self, names: list[str] | None = None) -> dict[str, Any]: ...
    def read_memory(self, address: str, size: int) -> dict[str, Any]: ...
    def disassemble(self, address: str, count: int) -> dict[str, Any]: ...
    def list_memory_maps(self) -> dict[str, Any]: ...
    def take_snapshot(self, name: str | None = None) -> dict[str, Any]: ...
    def restore_snapshot(self, snapshot_id: str) -> dict[str, Any]: ...
    def diff_snapshots(self, left_id: str, right_id: str) -> dict[str, Any]: ...
    def get_recent_events(
        self,
        limit: int = 100,
        event_types: list[str] | None = None,
    ) -> dict[str, Any]: ...
    def get_trace(self, limit: int) -> dict[str, Any]: ...
    def configure_event_filters(
        self,
        event_types: list[str] | None = None,
        address_ranges: list[tuple[str, str]] | None = None,
    ) -> dict[str, Any]: ...
    def get_state(self) -> dict[str, Any]: ...
    def capabilities(self) -> dict[str, bool]: ...
    def close(self) -> None: ...
